//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Legacy_DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_42039_legacyEntities : DbContext
    {
        public DB_42039_legacyEntities()
            : base("name=DB_42039_legacyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<politic> politics { get; set; }
        public virtual DbSet<religion> religions { get; set; }
        public virtual DbSet<address> addresses { get; set; }
        public virtual DbSet<admin_associates> admin_associates { get; set; }
        public virtual DbSet<associate> associates { get; set; }
        public virtual DbSet<country> countries { get; set; }
        public virtual DbSet<gender> genders { get; set; }
        public virtual DbSet<hobby> hobbies { get; set; }
        public virtual DbSet<job> jobs { get; set; }
        public virtual DbSet<message> messages { get; set; }
        public virtual DbSet<messagetype> messagetypes { get; set; }
        public virtual DbSet<school> schools { get; set; }
        public virtual DbSet<state> states { get; set; }
        public virtual DbSet<user_addresses> user_addresses { get; set; }
        public virtual DbSet<user_types> user_types { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<users_hobbies> users_hobbies { get; set; }
        public virtual DbSet<users_jobs> users_jobs { get; set; }
        public virtual DbSet<users_schools> users_schools { get; set; }
    }
}
