//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegacyConsole.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getReligions", ReplyAction="http://tempuri.org/IService1/getReligionsResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Data")]
        LegacyModel.DTO_religion[] getReligions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getReligions", ReplyAction="http://tempuri.org/IService1/getReligionsResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Data")]
        System.Threading.Tasks.Task<LegacyModel.DTO_religion[]> getReligionsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getGenders", ReplyAction="http://tempuri.org/IService1/getGendersResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Data")]
        LegacyModel.DTO_gender[] getGenders();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getGenders", ReplyAction="http://tempuri.org/IService1/getGendersResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Data")]
        System.Threading.Tasks.Task<LegacyModel.DTO_gender[]> getGendersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getPolitics", ReplyAction="http://tempuri.org/IService1/getPoliticsResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Data")]
        LegacyModel.DTO_politic[] getPolitics();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getPolitics", ReplyAction="http://tempuri.org/IService1/getPoliticsResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Data")]
        System.Threading.Tasks.Task<LegacyModel.DTO_politic[]> getPoliticsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getCountries", ReplyAction="http://tempuri.org/IService1/getCountriesResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Data")]
        LegacyModel.DTO_country[] getCountries();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getCountries", ReplyAction="http://tempuri.org/IService1/getCountriesResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Data")]
        System.Threading.Tasks.Task<LegacyModel.DTO_country[]> getCountriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getUserTypes", ReplyAction="http://tempuri.org/IService1/getUserTypesResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Data")]
        LegacyModel.DTO_user_types[] getUserTypes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getUserTypes", ReplyAction="http://tempuri.org/IService1/getUserTypesResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Data")]
        System.Threading.Tasks.Task<LegacyModel.DTO_user_types[]> getUserTypesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getMessageTypes", ReplyAction="http://tempuri.org/IService1/getMessageTypesResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Data")]
        LegacyModel.DTO_messagetypes[] getMessageTypes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getMessageTypes", ReplyAction="http://tempuri.org/IService1/getMessageTypesResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Data")]
        System.Threading.Tasks.Task<LegacyModel.DTO_messagetypes[]> getMessageTypesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getHobbies", ReplyAction="http://tempuri.org/IService1/getHobbiesResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Data")]
        LegacyModel.DTO_hobby[] getHobbies();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getHobbies", ReplyAction="http://tempuri.org/IService1/getHobbiesResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Data")]
        System.Threading.Tasks.Task<LegacyModel.DTO_hobby[]> getHobbiesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getSchools", ReplyAction="http://tempuri.org/IService1/getSchoolsResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Data")]
        LegacyModel.DTO_school[] getSchools();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getSchools", ReplyAction="http://tempuri.org/IService1/getSchoolsResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Data")]
        System.Threading.Tasks.Task<LegacyModel.DTO_school[]> getSchoolsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getJobs", ReplyAction="http://tempuri.org/IService1/getJobsResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Data")]
        LegacyModel.DTO_job[] getJobs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getJobs", ReplyAction="http://tempuri.org/IService1/getJobsResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Data")]
        System.Threading.Tasks.Task<LegacyModel.DTO_job[]> getJobsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getStates", ReplyAction="http://tempuri.org/IService1/getStatesResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Data")]
        LegacyModel.DTO_state[] getStates();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getStates", ReplyAction="http://tempuri.org/IService1/getStatesResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Data")]
        System.Threading.Tasks.Task<LegacyModel.DTO_state[]> getStatesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAddresses", ReplyAction="http://tempuri.org/IService1/getAddressesResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Data")]
        LegacyModel.DTO_address[] getAddresses();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAddresses", ReplyAction="http://tempuri.org/IService1/getAddressesResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Data")]
        System.Threading.Tasks.Task<LegacyModel.DTO_address[]> getAddressesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getMessages", ReplyAction="http://tempuri.org/IService1/getMessagesResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Data")]
        LegacyModel.DTO_message[] getMessages();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getMessages", ReplyAction="http://tempuri.org/IService1/getMessagesResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Data")]
        System.Threading.Tasks.Task<LegacyModel.DTO_message[]> getMessagesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getUserJobs", ReplyAction="http://tempuri.org/IService1/getUserJobsResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Data")]
        LegacyModel.DTO_user_job[] getUserJobs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getUserJobs", ReplyAction="http://tempuri.org/IService1/getUserJobsResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Data")]
        System.Threading.Tasks.Task<LegacyModel.DTO_user_job[]> getUserJobsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getUserAddress", ReplyAction="http://tempuri.org/IService1/getUserAddressResponse")]
        LegacyModel.DTO_user_address[] getUserAddress();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getUserAddress", ReplyAction="http://tempuri.org/IService1/getUserAddressResponse")]
        System.Threading.Tasks.Task<LegacyModel.DTO_user_address[]> getUserAddressAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getUserHobby", ReplyAction="http://tempuri.org/IService1/getUserHobbyResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Data")]
        LegacyModel.DTO_user_hobby[] getUserHobby();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getUserHobby", ReplyAction="http://tempuri.org/IService1/getUserHobbyResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Data")]
        System.Threading.Tasks.Task<LegacyModel.DTO_user_hobby[]> getUserHobbyAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getUserSchool", ReplyAction="http://tempuri.org/IService1/getUserSchoolResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Data")]
        LegacyModel.DTO_user_school[] getUserSchool();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getUserSchool", ReplyAction="http://tempuri.org/IService1/getUserSchoolResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Data")]
        System.Threading.Tasks.Task<LegacyModel.DTO_user_school[]> getUserSchoolAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAssociate", ReplyAction="http://tempuri.org/IService1/getAssociateResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Data")]
        LegacyModel.DTO_associate[] getAssociate();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAssociate", ReplyAction="http://tempuri.org/IService1/getAssociateResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Data")]
        System.Threading.Tasks.Task<LegacyModel.DTO_associate[]> getAssociateAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAdminAssociate", ReplyAction="http://tempuri.org/IService1/getAdminAssociateResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Data")]
        LegacyModel.DTO_admin_associates[] getAdminAssociate();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAdminAssociate", ReplyAction="http://tempuri.org/IService1/getAdminAssociateResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Data")]
        System.Threading.Tasks.Task<LegacyModel.DTO_admin_associates[]> getAdminAssociateAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getUser", ReplyAction="http://tempuri.org/IService1/getUserResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Data")]
        LegacyModel.DTO_user[] getUser(LegacyModel.DTO_user user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getUser", ReplyAction="http://tempuri.org/IService1/getUserResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Data")]
        System.Threading.Tasks.Task<LegacyModel.DTO_user[]> getUserAsync(LegacyModel.DTO_user user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/newLogin", ReplyAction="http://tempuri.org/IService1/newLoginResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Data")]
        LegacyModel.DTO_user[] newLogin(LegacyModel.DTO_login user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/newLogin", ReplyAction="http://tempuri.org/IService1/newLoginResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Data")]
        System.Threading.Tasks.Task<LegacyModel.DTO_user[]> newLoginAsync(LegacyModel.DTO_login user);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : LegacyConsole.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<LegacyConsole.ServiceReference1.IService1>, LegacyConsole.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LegacyModel.DTO_religion[] getReligions() {
            return base.Channel.getReligions();
        }
        
        public System.Threading.Tasks.Task<LegacyModel.DTO_religion[]> getReligionsAsync() {
            return base.Channel.getReligionsAsync();
        }
        
        public LegacyModel.DTO_gender[] getGenders() {
            return base.Channel.getGenders();
        }
        
        public System.Threading.Tasks.Task<LegacyModel.DTO_gender[]> getGendersAsync() {
            return base.Channel.getGendersAsync();
        }
        
        public LegacyModel.DTO_politic[] getPolitics() {
            return base.Channel.getPolitics();
        }
        
        public System.Threading.Tasks.Task<LegacyModel.DTO_politic[]> getPoliticsAsync() {
            return base.Channel.getPoliticsAsync();
        }
        
        public LegacyModel.DTO_country[] getCountries() {
            return base.Channel.getCountries();
        }
        
        public System.Threading.Tasks.Task<LegacyModel.DTO_country[]> getCountriesAsync() {
            return base.Channel.getCountriesAsync();
        }
        
        public LegacyModel.DTO_user_types[] getUserTypes() {
            return base.Channel.getUserTypes();
        }
        
        public System.Threading.Tasks.Task<LegacyModel.DTO_user_types[]> getUserTypesAsync() {
            return base.Channel.getUserTypesAsync();
        }
        
        public LegacyModel.DTO_messagetypes[] getMessageTypes() {
            return base.Channel.getMessageTypes();
        }
        
        public System.Threading.Tasks.Task<LegacyModel.DTO_messagetypes[]> getMessageTypesAsync() {
            return base.Channel.getMessageTypesAsync();
        }
        
        public LegacyModel.DTO_hobby[] getHobbies() {
            return base.Channel.getHobbies();
        }
        
        public System.Threading.Tasks.Task<LegacyModel.DTO_hobby[]> getHobbiesAsync() {
            return base.Channel.getHobbiesAsync();
        }
        
        public LegacyModel.DTO_school[] getSchools() {
            return base.Channel.getSchools();
        }
        
        public System.Threading.Tasks.Task<LegacyModel.DTO_school[]> getSchoolsAsync() {
            return base.Channel.getSchoolsAsync();
        }
        
        public LegacyModel.DTO_job[] getJobs() {
            return base.Channel.getJobs();
        }
        
        public System.Threading.Tasks.Task<LegacyModel.DTO_job[]> getJobsAsync() {
            return base.Channel.getJobsAsync();
        }
        
        public LegacyModel.DTO_state[] getStates() {
            return base.Channel.getStates();
        }
        
        public System.Threading.Tasks.Task<LegacyModel.DTO_state[]> getStatesAsync() {
            return base.Channel.getStatesAsync();
        }
        
        public LegacyModel.DTO_address[] getAddresses() {
            return base.Channel.getAddresses();
        }
        
        public System.Threading.Tasks.Task<LegacyModel.DTO_address[]> getAddressesAsync() {
            return base.Channel.getAddressesAsync();
        }
        
        public LegacyModel.DTO_message[] getMessages() {
            return base.Channel.getMessages();
        }
        
        public System.Threading.Tasks.Task<LegacyModel.DTO_message[]> getMessagesAsync() {
            return base.Channel.getMessagesAsync();
        }
        
        public LegacyModel.DTO_user_job[] getUserJobs() {
            return base.Channel.getUserJobs();
        }
        
        public System.Threading.Tasks.Task<LegacyModel.DTO_user_job[]> getUserJobsAsync() {
            return base.Channel.getUserJobsAsync();
        }
        
        public LegacyModel.DTO_user_address[] getUserAddress() {
            return base.Channel.getUserAddress();
        }
        
        public System.Threading.Tasks.Task<LegacyModel.DTO_user_address[]> getUserAddressAsync() {
            return base.Channel.getUserAddressAsync();
        }
        
        public LegacyModel.DTO_user_hobby[] getUserHobby() {
            return base.Channel.getUserHobby();
        }
        
        public System.Threading.Tasks.Task<LegacyModel.DTO_user_hobby[]> getUserHobbyAsync() {
            return base.Channel.getUserHobbyAsync();
        }
        
        public LegacyModel.DTO_user_school[] getUserSchool() {
            return base.Channel.getUserSchool();
        }
        
        public System.Threading.Tasks.Task<LegacyModel.DTO_user_school[]> getUserSchoolAsync() {
            return base.Channel.getUserSchoolAsync();
        }
        
        public LegacyModel.DTO_associate[] getAssociate() {
            return base.Channel.getAssociate();
        }
        
        public System.Threading.Tasks.Task<LegacyModel.DTO_associate[]> getAssociateAsync() {
            return base.Channel.getAssociateAsync();
        }
        
        public LegacyModel.DTO_admin_associates[] getAdminAssociate() {
            return base.Channel.getAdminAssociate();
        }
        
        public System.Threading.Tasks.Task<LegacyModel.DTO_admin_associates[]> getAdminAssociateAsync() {
            return base.Channel.getAdminAssociateAsync();
        }
        
        public LegacyModel.DTO_user[] getUser(LegacyModel.DTO_user user) {
            return base.Channel.getUser(user);
        }
        
        public System.Threading.Tasks.Task<LegacyModel.DTO_user[]> getUserAsync(LegacyModel.DTO_user user) {
            return base.Channel.getUserAsync(user);
        }
        
        public LegacyModel.DTO_user[] newLogin(LegacyModel.DTO_login user) {
            return base.Channel.newLogin(user);
        }
        
        public System.Threading.Tasks.Task<LegacyModel.DTO_user[]> newLoginAsync(LegacyModel.DTO_login user) {
            return base.Channel.newLoginAsync(user);
        }
    }
}
